export type IpadProps = {
    _id: number,
    name: string,
    price: number,
    color: string[],
    display: string,
    picture: string,
    chip: string[],
    batteryAndPower: string[],
    memory: string,
    storage: string,
    touchID: string,
    camera: string,
    audio: string[],
    operatingSystem: string,
    inTheBox: string[],
}